### ISSUE TITLE
It looks like a typo for l?

### ISSUE THREAD

**Issue by Eclipsedclaw** [mzks/lazyins#1]
File "/home/pi/.local/lib/python3.9/site-packages/lazyins/lazyins.py", line 46, in setup
    if 'unknown' in l:
NameError: name 'l' is not defined

**Comment by Eclipsedclaw** [comment]
Checked and fixed, for lazyins/lazyins.py line 46-48

`if 'unknown' in self.types:`
`        print('Unknown type(s) are included.')`
`        return`

**Comment by mzks** [comment]
Thank you very much. Fixed.
You can make pull-request and fork this repository for your usage, for your information.
